templates:
  sat_tmpl:
    node_type: sat
    image: library/frrouting/frr:v8.4.0
    start_commands:
    - chown -R frr:frr /var/log/frr
    - /usr/lib/frr/frrinit.sh start
    stop_commands:
    - /usr/lib/frr/frrinit.sh stop
    volumes:
    - frr_conf:/etc/frr
    - frr_log:/var/log/frr
    fixed_vNICs:
      eth0: {}
      eth1: {}
      eth2: {}
      eth3: {}
      eth4: {}
      eth5: {}
    resources:
      cpu_score: 1691
      memory: 4GB
  gs_tmpl:
    node_type: gs
    image: library/frrouting/frr:v8.4.0
    start_commands:
    - chown -R frr:frr /var/log/frr
    - /usr/lib/frr/frrinit.sh start
    stop_commands:
    - /usr/lib/frr/frrinit.sh stop
    volumes:
    - frr_conf:/etc/frr
    - frr_log:/var/log/frr
fixed_nodes:
  Sat0:
    template: sat_tmpl
    sat_id: 0
  Sat1:
    template: sat_tmpl
    sat_id: 1
  Sat2:
    template: sat_tmpl
    sat_id: 2
  Sat3:
    template: sat_tmpl
    sat_id: 3
  Sat4:
    template: sat_tmpl
    sat_id: 4
  Sat5:
    template: sat_tmpl
    sat_id: 5
  Sat6:
    template: sat_tmpl
    sat_id: 6
  Sat7:
    template: sat_tmpl
    sat_id: 7
  Sat8:
    template: sat_tmpl
    sat_id: 8
  Sat9:
    template: sat_tmpl
    sat_id: 9
  Sat10:
    template: sat_tmpl
    sat_id: 10
  Sat11:
    template: sat_tmpl
    sat_id: 11
  Sat12:
    template: sat_tmpl
    sat_id: 12
  Sat13:
    template: sat_tmpl
    sat_id: 13
  Sat14:
    template: sat_tmpl
    sat_id: 14
  Sat15:
    template: sat_tmpl
    sat_id: 15
  Sat16:
    template: sat_tmpl
    sat_id: 16
  Sat17:
    template: sat_tmpl
    sat_id: 17
  Sat18:
    template: sat_tmpl
    sat_id: 18
  Sat19:
    template: sat_tmpl
    sat_id: 19
  Sat20:
    template: sat_tmpl
    sat_id: 20
  Sat21:
    template: sat_tmpl
    sat_id: 21
  Sat22:
    template: sat_tmpl
    sat_id: 22
  Sat23:
    template: sat_tmpl
    sat_id: 23
  Sat24:
    template: sat_tmpl
    sat_id: 24
  Sat25:
    template: sat_tmpl
    sat_id: 25
  Sat26:
    template: sat_tmpl
    sat_id: 26
  Sat27:
    template: sat_tmpl
    sat_id: 27
  Sat28:
    template: sat_tmpl
    sat_id: 28
  Sat29:
    template: sat_tmpl
    sat_id: 29
  Sat30:
    template: sat_tmpl
    sat_id: 30
  Sat31:
    template: sat_tmpl
    sat_id: 31
  Sat32:
    template: sat_tmpl
    sat_id: 32
  Sat33:
    template: sat_tmpl
    sat_id: 33
  Sat34:
    template: sat_tmpl
    sat_id: 34
  Sat35:
    template: sat_tmpl
    sat_id: 35
  Sat36:
    template: sat_tmpl
    sat_id: 36
  Sat37:
    template: sat_tmpl
    sat_id: 37
  Sat38:
    template: sat_tmpl
    sat_id: 38
  Sat39:
    template: sat_tmpl
    sat_id: 39
  Sat40:
    template: sat_tmpl
    sat_id: 40
  Sat41:
    template: sat_tmpl
    sat_id: 41
  Sat42:
    template: sat_tmpl
    sat_id: 42
  Sat43:
    template: sat_tmpl
    sat_id: 43
  Sat44:
    template: sat_tmpl
    sat_id: 44
  Sat45:
    template: sat_tmpl
    sat_id: 45
  Sat46:
    template: sat_tmpl
    sat_id: 46
  Sat47:
    template: sat_tmpl
    sat_id: 47
  Sat48:
    template: sat_tmpl
    sat_id: 48
  Sat49:
    template: sat_tmpl
    sat_id: 49
  Sat50:
    template: sat_tmpl
    sat_id: 50
  Sat51:
    template: sat_tmpl
    sat_id: 51
  Sat52:
    template: sat_tmpl
    sat_id: 52
  Sat53:
    template: sat_tmpl
    sat_id: 53
  Sat54:
    template: sat_tmpl
    sat_id: 54
  Sat55:
    template: sat_tmpl
    sat_id: 55
  Sat56:
    template: sat_tmpl
    sat_id: 56
  Sat57:
    template: sat_tmpl
    sat_id: 57
  Sat58:
    template: sat_tmpl
    sat_id: 58
  Sat59:
    template: sat_tmpl
    sat_id: 59
  Sat60:
    template: sat_tmpl
    sat_id: 60
  Sat61:
    template: sat_tmpl
    sat_id: 61
  Sat62:
    template: sat_tmpl
    sat_id: 62
  Sat63:
    template: sat_tmpl
    sat_id: 63
  Sat64:
    template: sat_tmpl
    sat_id: 64
  Sat65:
    template: sat_tmpl
    sat_id: 65
  Sat66:
    template: sat_tmpl
    sat_id: 66
  Sat67:
    template: sat_tmpl
    sat_id: 67
  Sat68:
    template: sat_tmpl
    sat_id: 68
  Sat69:
    template: sat_tmpl
    sat_id: 69
  Sat70:
    template: sat_tmpl
    sat_id: 70
  Sat71:
    template: sat_tmpl
    sat_id: 71
  Sat72:
    template: sat_tmpl
    sat_id: 72
  Sat73:
    template: sat_tmpl
    sat_id: 73
  Sat74:
    template: sat_tmpl
    sat_id: 74
  Sat75:
    template: sat_tmpl
    sat_id: 75
  Sat76:
    template: sat_tmpl
    sat_id: 76
  Sat77:
    template: sat_tmpl
    sat_id: 77
  Sat78:
    template: sat_tmpl
    sat_id: 78
  Sat79:
    template: sat_tmpl
    sat_id: 79
  Sat80:
    template: sat_tmpl
    sat_id: 80
  Sat81:
    template: sat_tmpl
    sat_id: 81
  Sat82:
    template: sat_tmpl
    sat_id: 82
  Sat83:
    template: sat_tmpl
    sat_id: 83
  Sat84:
    template: sat_tmpl
    sat_id: 84
  Sat85:
    template: sat_tmpl
    sat_id: 85
  Sat86:
    template: sat_tmpl
    sat_id: 86
  Sat87:
    template: sat_tmpl
    sat_id: 87
  Sat88:
    template: sat_tmpl
    sat_id: 88
  Sat89:
    template: sat_tmpl
    sat_id: 89
  Sat90:
    template: sat_tmpl
    sat_id: 90
  Sat91:
    template: sat_tmpl
    sat_id: 91
  Sat92:
    template: sat_tmpl
    sat_id: 92
  Sat93:
    template: sat_tmpl
    sat_id: 93
  Sat94:
    template: sat_tmpl
    sat_id: 94
  Sat95:
    template: sat_tmpl
    sat_id: 95
  Sat96:
    template: sat_tmpl
    sat_id: 96
  Sat97:
    template: sat_tmpl
    sat_id: 97
  Sat98:
    template: sat_tmpl
    sat_id: 98
  Sat99:
    template: sat_tmpl
    sat_id: 99
  gs_0:
    template: gs_tmpl
    gs_id: 0
    fixed_vNICs:
      eth0: {}
      eth1: {}
  gs_1:
    template: gs_tmpl
    gs_id: 1
    fixed_vNICs:
      eth0: {}
      eth1: {}
      eth2: {}
  gs_2:
    template: gs_tmpl
    gs_id: 2
    fixed_vNICs:
      eth0: {}
      eth1: {}
links:
  engines:
  - walker_delta
  veth_pairs: []
